# Copyright (c) 2026 The Quicksilver developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit/.

# Usage: cmake -DBUILD_DIR=build [-DCONFIG=Release] [-DRESULTS=results.xml]
#              [-DMANIFEST=path] -P cmake/script/CheckCtestManifest.cmake
# RESULTS is CTest's --output-junit file, including for multi-config builds.
cmake_minimum_required(VERSION 3.22)
if(NOT DEFINED BUILD_DIR OR NOT EXISTS "${BUILD_DIR}/CMakeCache.txt")
  message(FATAL_ERROR "ctest manifest: BUILD_DIR must name a configured build directory")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
if(NOT DEFINED MANIFEST)
  set(MANIFEST "${CMAKE_CURRENT_LIST_DIR}/../../test/ctest-manifest.txt")
endif()
file(STRINGS "${BUILD_DIR}/CMakeCache.txt" cache_lines)
foreach(line IN LISTS cache_lines)
  if(line MATCHES "^([^#/:=]+):[^=]+=(.*)$")
    set("cache_${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
  endif()
endforeach()

# These identities normally live in generated metadata, not CMakeCache.txt.
# Read only the set() values we need; do not execute a build's CMake files.
foreach(identity IN ITEMS CMAKE_SYSTEM_NAME CMAKE_CXX_COMPILER_ID CMAKE_CXX_SIMULATE_ID)
  set(${identity} "${cache_${identity}}")
  if(NOT DEFINED cache_${identity})
    if(identity STREQUAL "CMAKE_SYSTEM_NAME")
      set(metadata_name CMakeSystem.cmake)
    else()
      set(metadata_name CMakeCXXCompiler.cmake)
    endif()
    file(GLOB metadata_files "${BUILD_DIR}/CMakeFiles/*/${metadata_name}")
    list(LENGTH metadata_files metadata_count)
    if(NOT metadata_count EQUAL 1)
      message(FATAL_ERROR "ctest manifest: expected one ${metadata_name} in ${BUILD_DIR}/CMakeFiles")
    endif()
    file(READ "${metadata_files}" metadata)
    if(metadata MATCHES "set\\(${identity} \"([^\"]*)\"\\)")
      set(${identity} "${CMAKE_MATCH_1}")
    endif()
  endif()
endforeach()
if(CMAKE_SYSTEM_NAME STREQUAL "" OR CMAKE_CXX_COMPILER_ID STREQUAL "")
  message(FATAL_ERROR "ctest manifest: missing platform or compiler identity")
endif()

set(condition_always TRUE)
foreach(pair IN ITEMS "tests:BUILD_TESTS" "gui:BUILD_GUI" "gui-tests:BUILD_GUI_TESTS"
    "bench:BUILD_BENCH" "fuzz:BUILD_FUZZ_BINARY" "vault:ENABLE_VAULT" "tx:BUILD_TX")
  string(REPLACE ":" ";" pair "${pair}")
  list(GET pair 0 condition)
  list(GET pair 1 option)
  set(condition_${condition} FALSE)
  if(cache_${option})
    set(condition_${condition} TRUE)
  endif()
endforeach()
# BUILD_FOR_FUZZING overrides these options without updating their cache values.
if(cache_BUILD_FOR_FUZZING)
  foreach(condition IN ITEMS tests gui gui-tests bench tx)
    set(condition_${condition} FALSE)
  endforeach()
  set(condition_fuzz TRUE)
endif()
set(condition_python FALSE)
if(NOT cache_CMAKE_DISABLE_FIND_PACKAGE_Python3 AND
    (cache_Python3_EXECUTABLE OR cache__Python3_EXECUTABLE))
  set(condition_python TRUE)
endif()
set(condition_linux FALSE)
set(condition_windows FALSE)
set(condition_msvc FALSE)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(condition_linux TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(condition_windows TRUE)
endif()
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
  set(condition_msvc TRUE)
endif()
set(condition_not-coverage TRUE)
if(cache_CMAKE_BUILD_TYPE STREQUAL "Coverage")
  set(condition_not-coverage FALSE)
endif()
# getenv() in gpu_parity_tests checks presence, even for an empty value.
set(condition_gpu-unset FALSE)
if(NOT DEFINED ENV{CUCKATOO_GPU_SOLVER})
  set(condition_gpu-unset TRUE)
endif()

function(matches_conditions expression output)
  string(REPLACE "," ";" terms "${expression}")
  set(matches TRUE)
  foreach(term IN LISTS terms)
    if(NOT DEFINED condition_${term})
      message(FATAL_ERROR "ctest manifest: unknown condition '${term}'")
    endif()
    if(NOT condition_${term})
      set(matches FALSE)
    endif()
  endforeach()
  set(${output} ${matches} PARENT_SCOPE)
endfunction()

file(STRINGS "${MANIFEST}" manifest_lines)
set(all_names "")
set(expected "")
foreach(line IN LISTS manifest_lines)
  string(STRIP "${line}" line)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  if(NOT line MATCHES "^([A-Za-z0-9_-]+)[ \t]+([a-z,-]+)[ \t]+([a-z,-]+)[ \t]+(.+)$")
    message(FATAL_ERROR "ctest manifest: malformed line '${line}'")
  endif()
  set(name "${CMAKE_MATCH_1}")
  set(registration "${CMAKE_MATCH_2}")
  set(skip "${CMAKE_MATCH_3}")
  set(reason "${CMAKE_MATCH_4}")
  if(name IN_LIST all_names)
    message(FATAL_ERROR "ctest manifest: duplicate name '${name}'")
  endif()
  list(APPEND all_names "${name}")
  matches_conditions("${registration}" enabled)
  if(skip STREQUAL "never")
    set(allowed FALSE)
  else()
    # Skip policies intentionally have a narrower vocabulary than registration.
    if(NOT skip STREQUAL "gpu-unset" AND NOT skip STREQUAL "msvc")
      message(FATAL_ERROR "ctest manifest: unknown skip policy '${skip}' for ${name}")
    endif()
    matches_conditions("${skip}" allowed)
  endif()
  if(enabled)
    list(APPEND expected "${name}")
    set(skip_${name} ${allowed})
    set(reason_${name} "${reason}")
  endif()
endforeach()

set(ctest_args --test-dir "${BUILD_DIR}" -N --show-only=json-v1)
if(DEFINED CONFIG)
  list(APPEND ctest_args -C "${CONFIG}")
endif()
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" ${ctest_args}
  OUTPUT_VARIABLE inventory ERROR_VARIABLE inventory_error RESULT_VARIABLE inventory_rc)
if(NOT inventory_rc EQUAL 0)
  message(FATAL_ERROR "ctest manifest: ctest inventory failed (${inventory_rc}): ${inventory_error}")
endif()
string(JSON registered_count LENGTH "${inventory}" tests)
set(registered "")
if(registered_count GREATER 0)
  math(EXPR last "${registered_count} - 1")
  foreach(index RANGE ${last})
    string(JSON name GET "${inventory}" tests ${index} name)
    if(name IN_LIST registered)
      message(FATAL_ERROR "ctest manifest: duplicate registered name '${name}'")
    endif()
    list(APPEND registered "${name}")
  endforeach()
endif()
set(active "")
foreach(condition IN ITEMS tests gui gui-tests bench fuzz vault tx python linux windows msvc not-coverage)
  if(condition_${condition})
    list(APPEND active "${condition}")
  endif()
endforeach()
list(JOIN active "," active)
list(LENGTH expected expected_count)
message("ctest manifest: ${expected_count} expected for ${active}, ${registered_count} registered")
set(offenders "")
foreach(name IN LISTS expected)
  if(NOT name IN_LIST registered)
    string(APPEND offenders "\n  missing: ${name}")
  endif()
endforeach()
foreach(name IN LISTS registered)
  if(NOT name IN_LIST expected)
    string(APPEND offenders "\n  unexpected: ${name}")
  endif()
endforeach()
if(NOT offenders STREQUAL "")
  message(FATAL_ERROR "ctest manifest: registration mismatch:${offenders}")
endif()
if(NOT DEFINED RESULTS)
  return()
endif()

# CTest's JUnit is a fresh, explicitly named artifact from this run. LastTest
# logs can be stale and do not reliably distinguish all not-run statuses.
# Test names are restricted above to XML-safe characters. Test output is escaped
# by CTest, so it cannot introduce a literal testcase/skipped/failure element.
file(READ "${RESULTS}" results)
if(NOT results MATCHES "<testsuite[ \t\r\n][^>]*tests=\"([0-9]+)\"")
  message(FATAL_ERROR "ctest manifest: RESULTS is not a CTest JUnit report")
endif()
set(report_count "${CMAKE_MATCH_1}")
set(seen "")
set(allowed_count 0)
set(offenders "")
while(results MATCHES "<testcase[ \t\r\n][^>]*>")
  set(header "${CMAKE_MATCH_0}")
  string(FIND "${results}" "${header}" start)
  string(SUBSTRING "${results}" ${start} -1 results)
  if(header MATCHES "/>$")
    string(LENGTH "${header}" length)
    set(block "${header}")
  else()
    string(FIND "${results}" "</testcase>" end)
    if(end LESS 0)
      message(FATAL_ERROR "ctest manifest: unterminated testcase in RESULTS")
    endif()
    math(EXPR length "${end} + 11")
    string(SUBSTRING "${results}" 0 ${length} block)
  endif()
  string(SUBSTRING "${results}" ${length} -1 results)
  if(NOT header MATCHES "[ \t\r\n]name=\"([A-Za-z0-9_-]+)\"")
    message(FATAL_ERROR "ctest manifest: missing or invalid testcase name")
  endif()
  set(name "${CMAKE_MATCH_1}")
  if(NOT name IN_LIST expected OR name IN_LIST seen)
    message(FATAL_ERROR "ctest manifest: unknown or duplicate result '${name}'")
  endif()
  list(APPEND seen "${name}")
  if(block MATCHES "<failure[ />]" OR block MATCHES "<error[ />]")
    string(APPEND offenders "\n  failed: ${name}")
  elseif(header MATCHES "status=\"(notrun|disabled)\"" OR block MATCHES "<skipped[ />]")
    if(skip_${name})
      math(EXPR allowed_count "${allowed_count} + 1")
      message("ctest manifest: allowed skip: ${name} (${reason_${name}})")
    else()
      string(APPEND offenders "\n  unexpected skip/not run: ${name}")
    endif()
  elseif(NOT header MATCHES "status=\"run\"")
    string(APPEND offenders "\n  unrecognized result status: ${name}")
  endif()
endwhile()
list(LENGTH seen seen_count)
if(NOT seen_count EQUAL report_count OR seen_count EQUAL 0)
  message(FATAL_ERROR "ctest manifest: RESULTS has ${seen_count} testcases, reports ${report_count}")
endif()
if(NOT offenders STREQUAL "")
  message(FATAL_ERROR "ctest manifest: results rejected:${offenders}")
endif()
message("ctest manifest: ${seen_count} results checked, ${allowed_count} allowed skips")
