// Copyright (c) 2026 The Quicksilver developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.
#include <tor/bundled_tor.h>

#include <logging.h>
#include <sync.h>
#include <tinyformat.h>
#include <util/fs_helpers.h>
#include <util/process/contained_child.h>
#include <util/readwritefile.h>
#include <util/strencodings.h>
#include <util/string.h>
#include <util/time.h>
#include <util/translation.h>

#include <chrono>
#include <memory>
#include <system_error>

#ifdef WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

namespace tor {

std::string BuildTorrc(const TorrcPaths& paths, int64_t owning_pid)
{
    std::string rc;
    rc += "# Generated by Quicksilver. Rewritten at every start; edits are lost.\n";
    rc += "DataDirectory " + paths.data_dir + "\n";
    rc += "ControlPort auto\n";
    rc += "ControlPortWriteToFile " + paths.control_port_file + "\n";
    rc += "CookieAuthentication 1\n";
    rc += "SocksPort auto\n";
    rc += "Log notice file " + paths.log_file + "\n";
    rc += "__OwningControllerProcess " + util::ToString(owning_pid) + "\n";
    return rc;
}

bool IsTorrcSafeValue(const std::string& value)
{
    if (value.empty()) return false;
    if (value.find_first_of("#\"\r\n") != std::string::npos) return false;
    if (value.back() == ' ' || value.back() == '\t') return false;
    return true;
}

ControlPortParse ParseControlPortFile(const std::string& contents, std::string& endpoint)
{
    bool saw_complete_line{false};
    size_t pos = 0;
    while (pos < contents.size()) {
        const size_t eol = contents.find('\n', pos);
        if (eol == std::string::npos) break;   // a partial write: wait for the rest
        std::string line = contents.substr(pos, eol - pos);
        pos = eol + 1;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        saw_complete_line = true;
        if (line.rfind("PORT=", 0) != 0) continue;
        const std::string candidate = line.substr(5);
        uint16_t port{0};
        std::string host;
        if (!SplitHostPort(candidate, port, host) || port == 0 || host.empty()) {
            return ControlPortParse::kMalformed;
        }
        endpoint = candidate;
        return ControlPortParse::kOk;
    }
    return saw_complete_line ? ControlPortParse::kMalformed : ControlPortParse::kIncomplete;
}

std::optional<fs::path> FindTorBinary(const fs::path& override_path,
                                      const fs::path& exe_dir,
                                      const std::string& path_env,
                                      char path_separator,
                                      const std::string& binary_name,
                                      const std::function<bool(const fs::path&)>& usable)
{
    if (!override_path.empty()) {
        if (usable(override_path)) return override_path;
        return std::nullopt;   // named and unusable: say so, do not run something else
    }
    if (!exe_dir.empty()) {
        // fs.h deliberately deletes operator/(path, std::string): appending a
        // std::string to a path is an encoding bug waiting to happen on Windows.
        const fs::path beside = exe_dir / fs::PathFromString(binary_name);
        if (usable(beside)) return beside;
    }
    size_t pos = 0;
    while (pos <= path_env.size()) {
        const size_t sep = path_env.find(path_separator, pos);
        const std::string entry = path_env.substr(pos, sep == std::string::npos ? std::string::npos : sep - pos);
        pos = (sep == std::string::npos) ? path_env.size() + 1 : sep + 1;
        // An empty PATH element means "the working directory" to some shells. A
        // candidate resolved against the CWD is not something a node should
        // execute, so skip it.
        if (entry.empty()) continue;
        const fs::path candidate = fs::PathFromString(entry) / fs::PathFromString(binary_name);
        if (usable(candidate)) return candidate;
    }
    return std::nullopt;
}

namespace {
//! How long to wait for Tor to report a control port. Tor writes this file
//! before it starts bootstrapping, so this bounds start-up, not the network.
//! Generous because a cold first run on a slow disk has to build its own data
//! directory first.
constexpr auto kControlPortTimeout{std::chrono::seconds{60}};
constexpr auto kControlPortPollInterval{std::chrono::milliseconds{100}};

Mutex g_bundled_tor_mutex;
std::unique_ptr<util::ContainedChild> g_bundled_tor GUARDED_BY(g_bundled_tor_mutex);

int64_t SelfPid()
{
#ifdef WIN32
    return static_cast<int64_t>(GetCurrentProcessId());
#else
    return static_cast<int64_t>(getpid());
#endif
}

//! The directory our own executable lives in, or an empty path when the platform
//! will not say. Only the SEARCH that consumes this is platform-neutral and
//! tested; asking the OS where we are cannot be.
fs::path SelfExecutableDir()
{
    // fs::path deliberately DELETES its std::string constructor (src/util/fs.h:
    // "Disallow std::string arguments to avoid locale-dependent decoding on
    // windows"), so the narrow branch goes through PathFromString rather than
    // the natural-looking conversion. The wide branch has no such problem: only
    // the narrow overload is deleted, and a wide string is what a path is made
    // of on Windows.
#ifdef WIN32
    wchar_t buf[MAX_PATH + 1];
    const DWORD n = GetModuleFileNameW(nullptr, buf, MAX_PATH);
    // n == MAX_PATH means the name did not fit and was TRUNCATED -- a truncated
    // path names a different file, or none, so it is a failure, not an answer.
    if (n == 0 || n >= MAX_PATH) return {};
    return fs::path(std::wstring(buf, n)).parent_path();
#else
    char buf[4096];
    const ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf));
    if (n <= 0 || static_cast<size_t>(n) >= sizeof(buf)) return {};
    return fs::PathFromString(std::string(buf, static_cast<size_t>(n))).parent_path();
#endif
}

bool IsUsableExecutable(const fs::path& p)
{
    std::error_code ec;
    if (!fs::is_regular_file(p, ec)) return false;
#ifndef WIN32
    return ::access(fs::PathToString(p).c_str(), X_OK) == 0;
#else
    return true;   // the check that would matter here is CreateProcess's own
#endif
}

std::optional<fs::path> LocateTor(const fs::path& override_path)
{
#ifdef WIN32
    constexpr char kPathSeparator{';'};
    const std::string kBinaryName{"tor.exe"};
#else
    constexpr char kPathSeparator{':'};
    const std::string kBinaryName{"tor"};
#endif
    const char* path_env = std::getenv("PATH");
    return FindTorBinary(override_path, SelfExecutableDir(), path_env ? path_env : "",
                         kPathSeparator, kBinaryName, IsUsableExecutable);
}
} // namespace

util::Result<std::string> StartBundledTor(const fs::path& datadir, const fs::path& override_path)
    EXCLUSIVE_LOCKS_REQUIRED(!g_bundled_tor_mutex)
{
    {
        LOCK(g_bundled_tor_mutex);
        if (g_bundled_tor) return util::Error{Untranslated("A bundled Tor is already running")};
    }

    const fs::path tor_dir = datadir / "tor";
    const fs::path torrc_path = tor_dir / "torrc";
    const fs::path port_path = tor_dir / "control_port";
    const fs::path log_path = tor_dir / "tor.log";
    const fs::path data_path = tor_dir / "data";

    // Tor reads an unquoted torrc value literally to end of line, so a path it
    // cannot round-trip has to be refused here rather than silently becoming a
    // different directory -- or, with a '#' in it, no directive at all.
    for (const fs::path& p : {data_path, port_path, log_path}) {
        if (!IsTorrcSafeValue(fs::PathToString(p))) {
            return util::Error{strprintf(_("The data directory path cannot be passed to Tor because it "
                                           "contains one of \" # or a line break: %s"),
                                         fs::PathToString(p))};
        }
    }

    const std::optional<fs::path> tor_binary = LocateTor(override_path);
    if (!tor_binary) {
        return util::Error{_("Bundled Tor is enabled but no usable 'tor' executable was found. "
                             "Install Tor (see doc/tor.md), place it beside the Quicksilver "
                             "executable, or set -bundledtorpath=<path>. To use a Tor you start "
                             "and configure yourself, set -bundledtor=0.")};
    }

    // TryCreateDirectories answers "did I create it", not "is it there": it
    // returns FALSE for a directory that already existed. Treating that as a
    // failure would have started Tor exactly once per datadir and refused every
    // run after the first.
    if (!TryCreateDirectories(tor_dir) && !fs::is_directory(tor_dir)) {
        return util::Error{strprintf(_("Cannot create the Tor directory %s"), fs::PathToString(tor_dir))};
    }
    // A previous run's file names a port nothing is listening on. Left in place,
    // it is read as this run's answer before Tor has written a word.
    std::error_code ec;
    fs::remove(port_path, ec);

    const TorrcPaths paths{fs::PathToString(data_path), fs::PathToString(port_path),
                           fs::PathToString(log_path)};
    if (!WriteBinaryFile(torrc_path, BuildTorrc(paths, SelfPid()))) {
        return util::Error{strprintf(_("Cannot write %s"), fs::PathToString(torrc_path))};
    }

    // Tor's own stdout is DISCARDED: it logs to the file the torrc names, and an
    // undrained pipe is how the solver bridge deadlocked with nobody reading it.
    auto child = util::ContainedChild::Spawn(
        {fs::PathToString(*tor_binary), "-f", fs::PathToString(torrc_path)},
        util::ChildStdout::kDiscard);
    if (!child) {
        return util::Error{strprintf(_("Failed to start Tor (%s)"), fs::PathToString(*tor_binary))};
    }
    LogInfo(HgLog::TOR, "tor: started bundled tor=%s torrc=%s\n",
            fs::PathToString(*tor_binary), fs::PathToString(torrc_path));

    // Every return below destroys `child`, whose destructor kills the group --
    // so no failure path here leaves a Tor running.
    const auto deadline = std::chrono::steady_clock::now() + kControlPortTimeout;
    for (;;) {
        const auto [ok, contents] = ReadBinaryFile(port_path);
        if (ok) {
            std::string endpoint;
            const ControlPortParse parsed = ParseControlPortFile(contents, endpoint);
            if (parsed == ControlPortParse::kOk) {
                LOCK(g_bundled_tor_mutex);
                g_bundled_tor = std::move(child);
                LogInfo(HgLog::TOR, "tor: bundled control port at %s\n", endpoint);
                return endpoint;
            }
            if (parsed == ControlPortParse::kMalformed) {
                return util::Error{strprintf(_("Tor wrote a control port file we cannot use: %s"),
                                             fs::PathToString(port_path))};
            }
        }
        // Checked BEFORE the deadline: a Tor that has already died must be
        // reported as dead, now, not as a minute of unexplained waiting.
        if (child->Exited()) {
            return util::Error{strprintf(_("Tor exited before reporting a control port; see %s"),
                                         fs::PathToString(log_path))};
        }
        if (std::chrono::steady_clock::now() >= deadline) {
            return util::Error{strprintf(_("Tor did not report a control port within 60 seconds; see %s"),
                                         fs::PathToString(log_path))};
        }
        UninterruptibleSleep(kControlPortPollInterval);
    }
}

void StopBundledTor()
    EXCLUSIVE_LOCKS_REQUIRED(!g_bundled_tor_mutex)
{
    std::unique_ptr<util::ContainedChild> child;
    {
        LOCK(g_bundled_tor_mutex);
        child = std::move(g_bundled_tor);
    }
    if (!child) return;
    // SIGKILL, not a graceful signal. Tor's own state is crash-safe, and the
    // onion service key is OUR file, uploaded over the control port, not
    // anything Tor has to flush. Killing the GROUP is what matters: tor can
    // spawn helpers, and a process handle would reach only the one process.
    LogInfo(HgLog::TOR, "tor: stopping the bundled tor\n");
    child->KillGroup();
    child->Wait();
}

} // namespace tor
