#!/usr/bin/env python3
#
# Generate Quicksilver HUD action icons from the shared Mercury SVG geometry.
#
# Mercury geometry comes from src/qt/res/src/quicksilver.svg. The generated
# source SVGs are kept beside the rest of the Qt vector assets for review, while
# the PNG outputs preserve the existing resource aliases used by the Qt UI.
#
# Copyright (c) 2026 The Quicksilver developers
# Distributed under the MIT software license, see the accompanying file COPYING
# or https://opensource.org/license/mit/.

from __future__ import annotations

import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BRAND_SVG = ROOT / "src/qt/res/src/quicksilver.svg"
SRC_DIR = ROOT / "src/qt/res/src"
ICON_DIR = ROOT / "src/qt/res/icons"
SIZE = 128


@dataclass(frozen=True)
class MercuryPrimitive:
    tag: str
    attrs: dict[str, str]


@dataclass(frozen=True)
class HudIcon:
    name: str
    output_png: str
    mercury_scale: float
    mercury_center_x: float
    mercury_center_y: float
    extras: tuple[str, ...]
    include_mercury: bool = True


def strip_namespace(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def mercury_primitives() -> tuple[str, list[MercuryPrimitive]]:
    root = ET.parse(BRAND_SVG).getroot()
    knockout = None
    for node in root.iter():
        if strip_namespace(node.tag) == "mask" and node.attrib.get("id") == "mercury-knockout":
            knockout = node
            break
    if knockout is None:
        raise RuntimeError(f"{BRAND_SVG} is missing mask id mercury-knockout")

    mercury_group = None
    for node in knockout:
        if strip_namespace(node.tag) == "g" and node.attrib.get("stroke") == "black":
            mercury_group = node
            break
    if mercury_group is None:
        raise RuntimeError(f"{BRAND_SVG} is missing the Mercury stroke group")

    stroke_width = mercury_group.attrib["stroke-width"]
    primitives: list[MercuryPrimitive] = []
    for child in mercury_group:
        tag = strip_namespace(child.tag)
        if tag not in {"path", "circle", "line"}:
            raise RuntimeError(f"unsupported Mercury primitive: {tag}")
        primitives.append(MercuryPrimitive(tag=tag, attrs=dict(child.attrib)))
    return stroke_width, primitives


def attrs_text(attrs: dict[str, str]) -> str:
    return " ".join(f'{key}="{value}"' for key, value in attrs.items())


def mercury_group_svg(stroke_width: str, primitives: list[MercuryPrimitive], icon: HudIcon) -> str:
    tx = icon.mercury_center_x - (512 * icon.mercury_scale)
    ty = icon.mercury_center_y - (512 * icon.mercury_scale)
    elements = "\n".join(
        f"      <{primitive.tag} {attrs_text(primitive.attrs)}/>"
        for primitive in primitives
    )
    return f"""    <g fill="none" stroke="#000000" stroke-width="{stroke_width}"
       stroke-linecap="round" stroke-linejoin="round"
       transform="translate({tx:.3f} {ty:.3f}) scale({icon.mercury_scale:.3f})">
{elements}
    </g>"""


def source_svg(stroke_width: str, primitives: list[MercuryPrimitive], icon: HudIcon) -> str:
    extras = "\n".join(icon.extras)
    mercury = mercury_group_svg(stroke_width, primitives, icon) if icon.include_mercury else ""
    provenance = (
        "Generated from src/qt/res/src/quicksilver.svg by contrib/devtools/gen-qt-hud-icons.py."
        if icon.include_mercury
        else "Generated by contrib/devtools/gen-qt-hud-icons.py for the Quicksilver HUD icon family."
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  Quicksilver HUD {icon.name} icon.
  {provenance}

  Copyright (c) 2026 The Quicksilver developers
  Distributed under the MIT software license, see the accompanying file COPYING
  or https://opensource.org/license/mit/.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="{SIZE}" height="{SIZE}" viewBox="0 0 {SIZE} {SIZE}">
  <g fill="none" stroke="#000000" stroke-width="8.5" stroke-linecap="round" stroke-linejoin="round">
{extras}
  </g>
{mercury}
</svg>
"""


HUD_ICONS = (
    HudIcon(
        name="transfer",
        output_png="send.png",
        mercury_scale=0.084,
        mercury_center_x=44,
        mercury_center_y=64,
        extras=(
            '    <path d="M 76 64 H 115"/>',
            '    <path d="M 98 47 L 115 64 L 98 81"/>',
            '    <path d="M 72 39 H 86"/>',
            '    <path d="M 72 89 H 86"/>',
        ),
    ),
    HudIcon(
        name="request",
        output_png="receive.png",
        mercury_scale=0.084,
        mercury_center_x=84,
        mercury_center_y=64,
        extras=(
            '    <path d="M 13 64 H 52"/>',
            '    <path d="M 35 47 L 52 64 L 35 81"/>',
            '    <path d="M 42 39 H 56"/>',
            '    <path d="M 42 89 H 56"/>',
        ),
    ),
    HudIcon(
        name="ledger",
        output_png="history.png",
        mercury_scale=0.073,
        mercury_center_x=64,
        mercury_center_y=64,
        extras=(
            '    <path d="M 28 81 A 43 43 0 1 1 101 46"/>',
            '    <path d="M 100 46 L 104 29"/>',
            '    <path d="M 100 46 L 84 41"/>',
            '    <path d="M 24 96 H 48"/>',
            '    <path d="M 80 96 H 104"/>',
        ),
    ),
    HudIcon(
        name="agent",
        output_png="agent.png",
        mercury_scale=0,
        mercury_center_x=0,
        mercury_center_y=0,
        extras=(
            '    <rect x="27" y="31" width="74" height="69" rx="14"/>',
            '    <path d="M 64 18 V 31"/>',
            '    <circle cx="64" cy="14" r="4" fill="#000000" stroke="none"/>',
            '    <circle cx="49" cy="59" r="5" fill="#000000" stroke="none"/>',
            '    <circle cx="79" cy="59" r="5" fill="#000000" stroke="none"/>',
            '    <path d="M 49 79 Q 64 89 79 79"/>',
            '    <path d="M 15 51 H 27"/>',
            '    <path d="M 15 77 H 27"/>',
            '    <path d="M 101 51 H 113"/>',
            '    <path d="M 101 77 H 113"/>',
        ),
        include_mercury=False,
    ),
)


def main() -> int:
    stroke_width, primitives = mercury_primitives()
    for icon in HUD_ICONS:
        src_path = SRC_DIR / f"hud_{icon.name}.svg"
        png_path = ICON_DIR / icon.output_png
        src_path.write_text(source_svg(stroke_width, primitives, icon), encoding="utf8")
        subprocess.run(
            ["rsvg-convert", "-w", str(SIZE), "-h", str(SIZE), str(src_path), "-o", str(png_path)],
            check=True,
        )
    print("qt hud icons regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
