#!/usr/bin/env python3
#
# Generate the Quicksilver sync-spinner animation frames.
#
# The status-bar spinner is original Quicksilver artwork: a 270-degree arc led by
# a detached head dot, drawn in the same stroke language as the rest of the
# Quicksilver icon family (round caps and joins, single flat colour). The Mercury
# brand glyph is deliberately NOT used here -- it is unreadable at the 16 px the
# status bar renders this at, and every frame is a rotation of the whole image,
# which a glyph would spin along with.
#
# Frame 0 is written to src/qt/res/src/spinner.svg so the artwork stays
# reviewable as vector source; the 36 frames are rotations of it about the
# canvas centre. The drawing fits inside the inscribed circle, so no rotation
# clips a corner.
#
# Qt recolours these through PlatformStyle::SingleColorIcon, which keeps alpha
# and replaces colour, so only the alpha channel of these frames matters.
#
# Copyright (c) 2026 The Quicksilver developers
# Distributed under the MIT software license, see the accompanying file COPYING
# or https://opensource.org/license/mit/.

from __future__ import annotations

import math
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = ROOT / "src/qt/res/src"
FRAME_DIR = ROOT / "src/qt/res/animation"

SIZE = 128
FRAMES = 36  # keep in sync with SPINNER_FRAMES in src/qt/guiconstants.h

CENTRE = SIZE / 2
RADIUS = 44.0
STROKE = 15.0
ARC_START_DEG = 0.0
ARC_SWEEP_DEG = 270.0
HEAD_LEAD_DEG = 45.0  # head dot sits this far ahead of the arc, inside the gap
HEAD_RADIUS = 10.0


def point_on_ring(degrees: float) -> tuple[float, float]:
    radians = math.radians(degrees)
    return (CENTRE + RADIUS * math.cos(radians), CENTRE + RADIUS * math.sin(radians))


def spinner_svg(rotation_deg: float) -> str:
    start_x, start_y = point_on_ring(ARC_START_DEG)
    end_x, end_y = point_on_ring(ARC_START_DEG + ARC_SWEEP_DEG)
    head_x, head_y = point_on_ring(ARC_START_DEG + ARC_SWEEP_DEG + HEAD_LEAD_DEG)
    large_arc = 1 if ARC_SWEEP_DEG > 180 else 0
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  Quicksilver sync spinner{'' if rotation_deg == 0 else f', frame at {rotation_deg:g} degrees'}.
  Generated by contrib/devtools/gen-qt-spinner.py. Original Quicksilver artwork.

  Copyright (c) 2026 The Quicksilver developers
  Distributed under the MIT software license, see the accompanying file COPYING
  or https://opensource.org/license/mit/.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="{SIZE}" height="{SIZE}" viewBox="0 0 {SIZE} {SIZE}">
  <g transform="rotate({rotation_deg:g} {CENTRE:g} {CENTRE:g})">
    <path d="M {start_x:.3f} {start_y:.3f} A {RADIUS:g} {RADIUS:g} 0 {large_arc} 1 {end_x:.3f} {end_y:.3f}"
          fill="none" stroke="#000000" stroke-width="{STROKE:g}" stroke-linecap="round"/>
    <circle cx="{head_x:.3f}" cy="{head_y:.3f}" r="{HEAD_RADIUS:g}" fill="#000000"/>
  </g>
</svg>
"""


def render(svg: str, destination: Path) -> None:
    subprocess.run(
        ["rsvg-convert", "-w", str(SIZE), "-h", str(SIZE), "-o", str(destination)],
        input=svg.encode("utf8"),
        check=True,
    )


def main() -> int:
    source = SRC_DIR / "spinner.svg"
    source.write_text(spinner_svg(0), encoding="utf8")
    step = 360.0 / FRAMES
    for frame in range(FRAMES):
        render(spinner_svg(frame * step), FRAME_DIR / f"spinner-{frame:03d}.png")
    print(f"qt spinner regenerated: {source.relative_to(ROOT)} + {FRAMES} frames")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
