#!/usr/bin/env bash
#
#  quicksilver-daemon The Quicksilver server.
#
#
# chkconfig: 345 80 20
# description: quicksilver-daemon
# processname: quicksilver-daemon
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/quicksilver-daemon, see below
if [ -f /etc/sysconfig/quicksilver-daemon ]; then
        . /etc/sysconfig/quicksilver-daemon
fi

RETVAL=0

prog=quicksilver-daemon
# you can override the lockfile via QUICKSILVER_DAEMON_LOCKFILE in /etc/sysconfig/quicksilver-daemon
lockfile=${QUICKSILVER_DAEMON_LOCKFILE-/var/lock/subsys/quicksilver-daemon}

# quicksilver-daemon defaults to /usr/bin/quicksilver-daemon, override with QUICKSILVER_DAEMON_BIN
quicksilver_daemon=${QUICKSILVER_DAEMON_BIN-/usr/bin/quicksilver-daemon}

# quicksilver-daemon opts default to -disablevault, override with QUICKSILVER_DAEMON_OPTS
quicksilver_daemon_opts=${QUICKSILVER_DAEMON_OPTS--disablevault}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $quicksilver_daemon $quicksilver_daemon_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
