#!/usr/bin/env bash
#
#  quicksilverd The Quicksilver server.
#
#
# chkconfig: 345 80 20
# description: quicksilverd
# processname: quicksilverd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/quicksilverd, see below
if [ -f /etc/sysconfig/quicksilverd ]; then
        . /etc/sysconfig/quicksilverd
fi

RETVAL=0

prog=quicksilverd
# you can override the lockfile via QUICKSILVERD_LOCKFILE in /etc/sysconfig/quicksilverd
lockfile=${QUICKSILVERD_LOCKFILE-/var/lock/subsys/quicksilverd}

# quicksilverd defaults to /usr/bin/quicksilverd, override with QUICKSILVERD_BIN
quicksilverd=${QUICKSILVERD_BIN-/usr/bin/quicksilverd}

# quicksilverd opts default to -disablevault, override with QUICKSILVERD_OPTS
quicksilverd_opts=${QUICKSILVERD_OPTS--disablevault}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $quicksilverd $quicksilverd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
