description "Quicksilver Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env QUICKSILVERD_BIN="/usr/bin/quicksilverd"
env QUICKSILVERD_USER="quicksilver"
env QUICKSILVERD_GROUP="quicksilver"
env QUICKSILVERD_PIDDIR="/var/run/quicksilverd"
# upstart can't handle variables constructed with other variables
env QUICKSILVERD_PIDFILE="/var/run/quicksilverd/quicksilverd.pid"
env QUICKSILVERD_CONFIGFILE="/etc/quicksilver/quicksilver.conf"
env QUICKSILVERD_DATADIR="/var/lib/quicksilverd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # quicksilverd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$QUICKSILVERD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run quicksilverd."
        echo "The setting must appear in $QUICKSILVERD_CONFIGFILE"
        echo
        echo "This password is security critical to securing vaults "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Quicksilver Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$QUICKSILVERD_PIDDIR"
    chmod 0755 "$QUICKSILVERD_PIDDIR"
    chown $QUICKSILVERD_USER:$QUICKSILVERD_GROUP "$QUICKSILVERD_PIDDIR"
    chown $QUICKSILVERD_USER:$QUICKSILVERD_GROUP "$QUICKSILVERD_CONFIGFILE"
    chmod 0660 "$QUICKSILVERD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$QUICKSILVERD_PIDFILE" \
    --chuid $QUICKSILVERD_USER:$QUICKSILVERD_GROUP \
    --exec "$QUICKSILVERD_BIN" \
    -- \
    -pid="$QUICKSILVERD_PIDFILE" \
    -conf="$QUICKSILVERD_CONFIGFILE" \
    -datadir="$QUICKSILVERD_DATADIR" \
    -disablevault \
    -daemon
